// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOxw-uZ-kc-epSvLvZEdTJC1-Rtqr34BQ',
    appId: '1:575694615691:web:d40a144bcdc4512f57108e',
    messagingSenderId: '575694615691',
    projectId: 'paparrocketchat',
    authDomain: 'paparrocketchat.firebaseapp.com',
    storageBucket: 'paparrocketchat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEiix2HHob1O9k19CpZiIfMMLIz7CVz1A',
    appId: '1:575694615691:android:1a39078b51abdca257108e',
    messagingSenderId: '575694615691',
    projectId: 'paparrocketchat',
    storageBucket: 'paparrocketchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN6_6K5CremTOrSqOt5j26Y-CbqqkkU2Y',
    appId: '1:575694615691:ios:13a0023313757ef057108e',
    messagingSenderId: '575694615691',
    projectId: 'paparrocketchat',
    storageBucket: 'paparrocketchat.appspot.com',
    iosClientId:
        '575694615691-ki22smaue9602kkt4norclkrmia0fktu.apps.googleusercontent.com',
    iosBundleId: 'com.example.week8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN6_6K5CremTOrSqOt5j26Y-CbqqkkU2Y',
    appId: '1:575694615691:ios:6032e8d83a8e611157108e',
    messagingSenderId: '575694615691',
    projectId: 'paparrocketchat',
    storageBucket: 'paparrocketchat.appspot.com',
    iosClientId:
        '575694615691-f8bpvissp8p7vi198372blbj14hs0mq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.week8.RunnerTests',
  );
}
